global:
  resolve_timeout: 5m
  smtp_smarthost: "__GRYT_SMTP_HOST__:__GRYT_SMTP_PORT__"
  smtp_from: "__GRYT_SMTP_FROM__"
  smtp_auth_username: "__GRYT_SMTP_USER__"
  smtp_auth_password: "__GRYT_SMTP_PASS__"
  smtp_require_tls: true

route:
  receiver: email
  group_by: ["alertname"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h

receivers:
  - name: email
    email_configs:
      - to: "__GRYT_ALERT_EMAIL__"
